## Synopsis of Somali Fisheries
## Fisheries in Somalia

## Introduction
Somalia is located in a highly productive upwelling area. Somali fishers use traditional fishing methods to catch coastal large pelagic fishes. Domestic fishey sector is poorly managed due to lack of effective fisheries policy. Indeed, the fisheries regulations are so outdated. increase demand for fishery products. one of the richest fishing grounds in the region Bigeye and Albacore tuna. The sector plays in terms of nutrition, income, employment and earning foreign exchange it plays a much bigger role in the economies of many coastal area. Although some portion of the handgear fishery is recreational, all giant tuna is sold, and therefore is also commercial.

## Foreign Fishing
The Ministry of Fisheries and Marine Resources (MFMR) issued 41 fishing licences to Foreign vessels to engage in fishing activities in the Somali EEZ without having a well defined plan to to monitoring , control and surveillance.
Currently Chinese are fishing in Somali EZZ using longline, purse seines and trawls. and sometimes operating within coastal waters. This increased conflict and competition for fish between the foreign fleets and local fisherfolks. Increased fishery overexploitation and habitat degradation by foreign commercial fishing are threatening Somalia's coastal and marine resources. In the western Indian Ocean, there is a growing China commercial fishery for tuna that operates both within and beyond the Somali Exclusive Economic Zone. cause particular concern within the domestic fishing industry in Somalia. which put domestic fishers direct competition with foreign fishing companies. 
Training Somali fishermen to use foreign technology. the regulations, and management measures needed to address problems in highly migratory species fisheries. The fishing pressure resulting from offshore fisheries is hard to estimate due to lack of data on size of foreign fleets and their annual.
These vessels may target either tropical (yellowfin and bigeye tuna) or subtropical (albacore tuna) species.

Three decades of illegal fishing: Challenges and Opportunities
## Indentification of issues
1- To identify key issues to that contribute the current situation. 
2- Establish Somalia tuna policy that includes highly migratory species as tuna species, marlins, oceanic sharks, sailfishes and swordfish.
3- Establish unified national fisheries data collection. 
Lack of historical data and inefficient government spending
Somalia needs to develop improved gear and methods to increase catch, and establish TAC level for each fish stock.
IUU fishing in the Western Indian Ocean
Somalia should not license foreign commercial fishing companies. Offshore tuna fishing licences launched in late 2018. Current system of licensing lack transparency and accountability. illegal vessels just recently denied the right of Somali fishers in Puntland to fish for lobster off this coast. In the meantime Somalia can generate revenue from with enforcing strict license conditions. who have used the media as a tool to mislead public. This was done to prevent the public from learning of inadmissible evidence through media reports. Need to address new issues that arise. and the fishery is important to all 6 three wecoast states.

## Fisheries management approach
Future approaches to manage the sector can be Ecosystem-based management and co-management but must be consulted dialogue, engagement, and collaboration with fisherfolks, as well as a range of diverse stakeholders.
ways in which seafood is caught, processed, distributed, marketed, retailed, and consumed in Somalia. and marketing commercially valuable species. 
The proposed legislation must protect the right of Somali fishers. community fisheries management. 
New Zealand now has a management system capable of protecting our fisheries resources against overfishing.
For coastal states like Somalia it is a 'give with one hand, take away with the other' situation. 
The purpose of the Act was to prevent overfishing , especially by foreign fleets , and to allow overfished stocks to recover.

## Somalia participationin the Indian Ocean Tuna Commission (IOTC)
Indian Ocean Tuna Commission is an intergovernmental organisation provides scientific information and management recommendations for stocks of yellowfin tuna develop quotas for HMS based on the total allowable catch (TAC) .
Quota Allocations is required.
Somalia has not been an active participant in IOTC due to lack of marine professionals and adequately trained personnel. 
IOTC has failed to take into account coastal state considerations, and, in many instances, has failed to successfully manage these species. IOTC has failed to take into account developing coastal state interests.
Extinctions of marine fish, unthinkable even a few years ago, now appear possible.  
According to Omar, the IOTC has ignored the warnings of the biologists and allowed overfishing of tuna.
All I ask is that the EU end'give with one hand, take away with the other' situation.
I am not certain it has ever been discussed. 

## Fishery Management Plan (FMP)
## Somalia lobster industry 
## Rock Lobster Fishery Management Plan (FMP)
You can't deny obvious facts. 
Biological Resources

References
moxor ( boswellia sacra ) , which yields an incense called beeyo , or ' Somali - type olibanum in the international trade jargon', and yagcar. 
scale fishing takes place along the coast of Somaliland, mostly centred in Berbera, Seylac, Maydh and Laasqoray.
############################################################## Twitter Space ############################################################################

## History of Somali fisheries ##
## Waan idin salaamay dhamaan
○ Kuligeen wa ognahay in Somalia ey leedahay 3333km long coast-line. (we have the longest coastline in maindland Africa)
○ Exclusive economic zone (EEZ) oo isna aad u balaaran laguna qiyaaso 831,000 square kilometers. (million square km)
○ Somali coastal waters are one of the most resource rich fishing grounds in the world because of 
-the presence of a continental shelf and (google map ku tusi kara qeybta satellite view)
-the Somali current (draws the nutrient-rich water up from below) flowing the along the coast. 

The seasonal (from March to May, and September to November) 
+ upwelling of highly migratory schools of fish (e.g., tuna) along the northern Somali coastline made the lucrative fish easy to catch in abundance.
○ Somali waters are an important breeding ground for many migratory fish species such as:  important spawning area (both spawning grounds and feeding grounds)
+ tunas and tuna-like species (migratory fish species)
-major market species of tunas such as albacore tuna, -bigeye tuna, -skipjack tuna and -yellowfin tuna.

+ large ocean pelagic billfish species, such as marlin and sailfish, is the most glamorous, and expensive (Sportfishing in Kenya - Paper)
-Swordfish
-Striped Marlin
-Blue Marlin
-Black Marlin
-Sailfish / Shortbill spearfish (vulnerable species)
+ other commercial species (reef fishes- Red snapper, grouper, jacks ), you name it.
+ other species such as sharks and rays
+ Rock Lobster
+ Shrimp
+ Other nverts in general (Crabs)
+ Cetaceans mammals oo ka kooban different (whales and dolphins).

## Somalis and fishing ##
○ Final years of Italian rule in Somalia (present-day Somaliland aside), 
-state and private enterprises started to develop the marine poten-tial of the country, 
+ especially around the tip of the Horn between Las Qorey and ‘Aluula.
○ An Italian firm is attempting to establish a fish canning and fish meal factory here; as to the indigenous fishermen, a small start has been made by equipping a... 
○ Nevertheless, the Somalis are not traditionally fishermen, nor have they been consumers of fish.
○ Despite its 3,200km coastline, Somalia today has only a small fishing industry using traditional fishing methods.
○ Somalis on the whole are not great fish eaters even with the richness of their coastal waters.
○ Because of this, the country did not seriously engage in commercial fishing until the 1970s. 

## Employment ## Small-scale fisheries (SSF)
○ Fishing employs a small number of people in Somalia, mainly in the north.
○ According to Haakonsen, the number of full-time and active fishermen in Somalia between the late 1970s and early 1980s
+ranged from 2,600 to 4,000; and at least 90,000 people (about two percent of the population) depended fully or in part on fisheries along the coast.
○ About 12,000 persons engage in fishing, most of them for subsistence. (now 70,000).  
○ A small fishing industry has begun in the north where tuna, shark, and other warm-water fish are caught.
○ Exports of fish, dried, salted or canned, do not exceed 1% of all exports in value.
○ Official export records are largely unavailable.
## Commercial fishing era ##
○ Fisheries The development of commercial fishing dates back to 1974 when SomaliSoviet Joint Venture " SOMALFISH wis started.
+ operated ten deep-sea factory trawlers.
○ The joint Somali - Soviet fishing company, set up in mid-1973.
○ The fishing industry is faced on an agreement with the Russians in which a joint Somali - Soviet fishing fleet operates each taking 50 per cent of the catch.

○ then 1981 Somali-Italian joint company SOMITFISH resumed in 1987 as Somali High Seas Fishing Company (SHIFCO) with Italian-built and refurbished trawlers.

○ To combat the drought and famine of the 1970s, the military government of General Mohamed Siad Barre launched: 
-an ambitious program of resettling some fifteen thousand of the most affected nomadic communities of the interior to coastal settlements.
○ At the same time, improved distribution and marke ing facilities are being introduced – initially in Mogadishu ani later extended to other parts of the country. 
○ Further, the 1974 Co-operatives Law was also extended to fishing, and a joint Soviet / Somali firm (Somalifish), with ten Soviet trawlers, was created.
○ Fishing cooperatives were created in 1974.
○ The Swedes have provided vessels for shallow and deep water fishing and they have given training to Somali crews.
○ In 1982, private companies were permitted to begin business.
○ A policy to encourage private ownership of vessels and gear was introduced in 1983.
○ The fish canning plant at Alula has ceased operating.

○ MFMR 1980 and 1990, the government restricted industrial-scale fishing to no more than eighteen vessels at a time per its calculation of maximum sustained yield (MSY).
○ Shaqo abuurka At least 30 percent of the workforce of a vessel –during its fishing sojourn in Somali waters – were expected to be Somalis from the Ministry’s employee roster.

## IUU Before collapse
○ IUU Ali Farah recalls a case when about fiftyJapanese vessels came for the highly migratory tuna, but only fifteen of them were licensed in Somalia.
When the government collapsed in January 1991, the five fishing trawlers and a refrigerated transport vessel of SHIFCO 
-(the last in a long line of joint ventures between the Somali government and its foreign partners) became private ventures of the company’s last manager, Hassan Munyo.
-The Somali government separately owned and operated two trawlers named Awdal and Ras Asir that also fell into private hands following the escalation of the civil war.
-Joining his older brother’s lobster fishing business that had been operational since the 1980s and that later became the Northeast Fishing Company (NEFCO),126
## State Collapse ##
○ When the Somali government collapsed in 1991, there was a period when the waters off Somalia were illegally used as a ... 
○ Waste and dump it overboard, and then start fishing, taking home very large catches of illegally caught Somali fish.
○ After Somalia's collapse into civil war in 1991, some Somalis began to steal the odd small fishing boat.
○ Reported that regional administrations as well as individual warlords sold access rights to individual vessels

and companies,
○ But over time they attracted many European and Asian fishing vessels, whose exploitation depleted fish stocks. 
○ Longliners, -which are quite small, do fish illegally in Somali waters, especially in the months after October when monsoon winds draw ... 

++++>> What are the connections between IUU fishing and piracy in Somalia? 
○ Many pirates started as fishermen. As Ms. Petretto points out, Somalia's fishing waters used to be a source of community income. 
○ This practice reportedly has been going on in Somalia since the early 1990s (UNEP 2005,33).... 
○ In light of the estimated scale of IUU fishing in Somali waters, both in terms of 
-the number of vessels and 
-the size of the illegal catch,
○ These fishermen have violated the external sovereignty of Somalia by fishing its internationally recognised fishing zones.
○ Within 75 days of fishing, each ship gets up to 420 tons of fish out of Somali waters. The catch is worth 6.3 million U.S. dollars.
○ To stop illegal fishing, locals have begun to arm themselves and their boats and to keep watch on the coast. 
○ The Puntland administration began to issue its own fishing licences in January 2000 , having hired Bermuda - based security firm Hart
○ Licence sales continued to provide substantial hard currency revenues (issued by hogaamiye koxeed, oday dhaqameed, iyo mamulada qaar)

## Potential of the sector 
○ Somalia's maximum sustainable fish catch has been estimated at 180 , 000 tonnes/year of all varieties.
The estimated potential catch each year of these resources is 180,000 to 200,000 tons and is made up of:
-Large pelagic fish,
-small pelagic fish, 
-large demersals, 
-sharks, and rays.
-Lobsters, shrimp, squid, 
-cuttlefish, octopus, and 
-swimming crab 

○ Waaagi dowlada identification of fishes caught 97 fish species classified/identified (trawl fisheries).
○ During the period 1989-93 the longline catch can be estimated to 6000 to 8000 t/ year in the Somali LME.  
○ Although the nutritional status of the refugees improved over the year as a result of better food supply, canned fish. 
○ Great potential contribution to economic 
○ Employment and livelihood opportunities within the fishing community 
○ Dhlinyarada ganacsiyada yar yar ka sameeyay waad aragteen. 
○ Gnacasatada waawey advice siiyay iyo qaabka u invest gareesan laheeyeen sectorka.

## Challenges ## Challenges in the Fishing Industry ##
I will point out some of the outstanding challenges
complexity of the outstanding problems 

## instutional
○ Lack of management and enforcement
○ Lack of capacity amongst the ministries staff (wrong people is placed into position). No one is sufficient without the other two. (work collectively)
○ The condition of marine fisheries today (highlighting both marine ecosystems and marine life esp. fish species)

No biological data (the need for trained biologist) or someone with fisheries background. (Scientist or researcher)
+ Spawning, migration, recruitment to the fishery, age of recruitment, population structure, growth, emigration from fishing grounds, discussed from 
+ data on distribution of catches 
○ and even Traditional Data ayan jirin 
 No unified system of data collection
 most wa estimation 
○ The destruction of the habitat of several fish species could threaten future catches. 
-Geographic areas that are under particular stress (Three dacdes of illegal fishing)
## About sector
○ Primitive fishing technologies ()
○ Lack of adequate and reliable data == (Estimation mainly)
○ Lack of marketing  

## Licensing systenm 
○ it has been estimated that “700 foreign- owned vessels are fully engaged in unlicensed fishing in Somali waters” (FAO n.d.).
○ These vessels have been able to exploit Somalia's offshore living resources with “near impunity”
○ These vessels change its flag of registry and continue fishing
The worst thing happens when Somalia acts both as a coastal state (fishing grounds- and issue licence) and as a flag state).
○ Corruption sandareero yar laga qaadanayo 

These problems are more than three decades old
EU Franch and Spainish tuna seiners and 17 long-liners) from 65 previously agreements with foreign fishing fleets. 
But many of the questions asked three and four decades ago remain unanswered; new problems have been identified.
, and it is now clear that a “ business as usual strategy will not solve them.


The dumping of radioactive, industrial, medical, and electronic
unequal state-to-state relations and attendant predatory corpo-rate
put Somalia’s annual losses at a little over USD 300 million.71
## Dowlada hada jirta
Foreign fishing now allowed After several years of uncertainty.
○ Sanadki sadexaad aya la bixinaya wax lagu qabtayna ila hada lama yaqaan. (ogaada dowlada waxey noosheegtay kalumeysiga maxaliga aya lagu xoojinaya)
Goanki ugu danbeeyay ee suqa itoobiya kaluun logu dhoofiyay wali maclimaad badan kama hayo 
○ Somalia fisheries sector - Annual economic value $135m USD (wasaarada)
○ Fish exports were valued at over USD 600 million. (wa freshwater fish) marka (Another repackage hub) Like Oman, Thailand, UAE ayuunbey ila muuqata 
diyaarado waweyn wa heestaan facilities waa heystaan oo already kaluun ayeyba dhoofiyaan. Marka waxey ila muqata iney high priced market la target gareen doonan.

From a financial point of view dadka kuxeel dheer iyo walaalka barnaamijka igula jira ayan u deynayaa.

## Fisheries sector development -recommendationskeyga and the way forward- ##
Fisheries development strategies, 
○ From simple ideas of modernising the production equipment (boats and gear) Somali fishermen would require nets, fishing lines, and boats.
o Complex programmes involving management and institution building. Fishery development has been mainly directed towards increasing fish production. 

Focus on the identifiable problems.
○ I would not say they have made absolutely no progress, but I agree that the progress so far has been disappointing.
○ Building on the successful dimensions of what has been done so far (Somali fisheries monitoring center). (waxa positive ah mfmr) (Thailand fisheries monitoring Center, 2019). 
○ Oday cadaan oo adviserka wasaarada kaluumeysiga ayan isku aragnay:
3 days conference ah iyo waliba aan kawada qeyb galnay traning 5 maaalmood ah oo Fisheries monitoring control and surveillance (MCS)
+aan usheegay in Somalia u baahantahay centerkan ookale (labada building iyo technology ey isticmaalayaan)

○ Establish in the area of management information systems and statistical policy (Sudan lesson)
○ Innovative ways [relatively inexpensive methods and tools that have already been successfully applied in developing countries]
○ Collection of this information would help with planning of fishery policies. (always changing)


○ Seafood production techniques. (Investment waliba ganacsatada). wax jiheeyo ayey la'yihiin oo ka gada sectorka.

Reconciling 
Marka to bridge the interests of government for the need for hard currency revenues and longer term developmental approaches.
(regulations is the deal). Waan ka shaqeeyay Trawlers oo masaarida leeyihiin oo Sudan ka shaqeeya.
As a observer oo Fisheries Administration Sudan ka socda. ardayda fursad usiin jiray iney ku train gareyaan data collection. 
Expertska dhan waa diiden saaso ey tahay dowlada wa ogolaatay ayado fiirineysa lacagta.
Lkn regulationka aya wanaagsana at least oo geographical locations looxadiday ayey jariifayeen
most of it waxey ahaayeen soft bottom oo marine structures lama bur burneen inta badan. 
Lkn bycatchka aya high ahaa (non target). 

This approach is called co-management
○ Process of community-based co-management from its beginning, through implementation, to turnover to the community.


With the recognition of a 200-nautical-mile jurisdictional zone, or EEZ, for coastal States in the UN Law of the Sea Convention, 
○ coastal States have gained the right to: 
-establish conservation and 
-management measures. 

## talooyinka marka
oon marwlabana usheego
Cooperation ayaan u baanahay (si qaldan oo musuqa lacagaha lagu kala qaadana waad u wada shaqeysaan) 
+ marka cooperation at the interagncy and national level (FMS)
Define the problem
○ Identifying where improvements are possible (right now)

Limitation of infretructure waa lagu qaadana lkn wax badan oo ey qaban karaan aya jira 
○ legislation and regulations (include lessons learned during civil war and lessons from other nations).
-Fisheries law update -detailed- (they are working on it) waxyaabaha an ku push gareenay oon kala hadlay ayey kamid aheed since 2014

○ Actions on forein fishing vessels (mar walba xalka waxow ka bilaabana Somalia)
○ New problems have been identified (Previously agreements with foreign fishing fleets)
Domestic fisheries waa sugi karaa inta wax lo hor marinaa 
- Use existing insturments (opportunities for regional coordination). Fursaha inan ka faideysano. Lead ayaan ka noqon karnaa. 
- explore external examples to derive lessons that can applied in the country. Gambia oo SS ey saaciday. 
- Adivsorki World Bank uso direen Somaalia oo Thailad igu sheegay ayan dhowaan weydiiyay it seems like this is forgotten unfortunately. 
-  I can not see anything improving in the near future ayow ii raaciyay. 

This latter regulation will permit the National Marine Fisheries Service to monitor the catch per species on an annual basis and regulate
stock assessment and modelling


○ European Union Naval Force (EU NAVFOR) Somalia-Operation ATALANTA is the European Union 
-Counter-Piracy operation off the coast of Somalia 
-Mandate for monitporing fishing vessels 

-Marka waxaan ku jirnaa 'give with one hand, take away with the other' situation.
-China the is doing the same. 

○ Turkey - for the patrol support
○ Dhilnyarada wadanka wax ku bartay iyo kuwa dibadaha fursad siiya ayado qualification kaliya loo eegayo.

Fisheries Conservation and Management Act
## Fishery Management Plan (FMP)
## Somalia lobster industry 
## Rock Lobster Fishery Management Plan (FMP) 5 species 
Monitoring of Somali rock lobster fishery
## One fact
Just look at the western Australia rock lobster fishery with half the extent of the habitat of Somalia, only 3 of the species where Somalia has all 5 and for Australia worth $700m USD per year. All wa wild-catch. 

it has been heartbreaking to watch the losses wadankeena ku dhacaya. 
Wadankeena has been wasting this resource.

Fariinteyda ugu danbeysa marka:
- Ashkaasta tageera in academia waliba kuwa key fileds baranaaya oo wadanka wax ka badalo doona
-waxa kasi muhiimsan -invest in marine instutions waliba jaamacada ummada oo hada bilowday (invest in education in general si uga baxno)
-Inad buugag u keentaan 
-Lab Facilities
iyo si walba ood u caawin kartaan

Maclumaadka aad ogateen la share gareeya public in all outrech tools aad heli kartaan 
Twitter handle gaar ah ayaan u sameeyay oo barta twitterka ah walal Nedeef ayan ka codsana inow idinla share gareeyo.
Websitena waan u sameyanaya mardhow inshAallah.
Halkaas kala socda and spread the word.

Ugu danbeyn thanks both nadeef and mohamed for organizing this wonderful event.  
Mahadsanidiin dhageystayaasha dhamaan. 
## Mahadsanidiiin ##
I have enough information to do my job well.



## statement 
I would like to make one or two comments , but I would like to make it very clear that I speak as an individual observer. 
my first official act is to make a statement in exercise of right of reply to the statement made by the mfmr
 I just want to make clear that we're not talking about any abrogable legal responsibility .
I read this statement with some concern, and, I might say, with very sincere ...
The State Tribunal tries high - ranking government officials accused of breaking the law.
Surely the honourable senator is not suggesting that we in this Parliament break our own laws.
presumably intended not to encourage police officials to break the law.
It is shocking because the In both cases , the Conservatives have demonstrated once again lack of action by the Conservatives.
Once again , the Chinese government had refused to elaborate on its commitment to Cambodia.
When we talk about illegal fishing we are not just talking foreign vessels. 
So what you do when Somali-owned vessels 
what happends when foreign vessels practice violates the agreement? 
Existing law already provides
They don't know a damn thing about what they are doing. 
The Mishnah's authorities ignore the discrepancy in the specific acts of commingling referred to by the separate sources.
mfmr still trying to hide some facts. 
it is my responsibility to provide the closing remarks for this
We, as Parliamentarians, have a responsibility to inform and improve public debate and understanding.
giving of a misleading statement 
The failure by the Ministry to submit an
The Ministry of Fisheries and Marine Resources falied to challenge facts and to prove itself innocent .
of proving itself innocent of the allegations implicit in the individual issues. .
the most shocking part of his demagogic speech was his promise of enduring peace when he was engaged in.
I want to keep it that way .
One of the most-shocking claims made by the mfmr is 
I am not surprised Ministry's failure to challenge 
give you gentlemen all the evidence possible and you have asked all kinds of questions so that no one can escape.

## the legality of the trawlers
the FHS reply did not provide any supporting documentation for its position .
In addition, the reply did not include a signed oath or declaration.
providing evidence of continuing corruption 
It seems to me that what it says is, if you broke the law before , you can continue to break the law . That is the way I view the safe haven.
I think that a better public understanding of the situation certainly is of great benefit to this committee today,
Perhaps we could try to get a better understanding of why it takes you longer than Ann to do the same job.
In the north Atlantic there was a dispute between Iceland, which claimed to reserve to its own nationals the right to exploit the excellent fishing grounds.
France and other continental Member States claimed " historic rights " in fishing grounds situated in British waters. 
You make the best of a situation because you understand how the competition works . ... 
As you get better at reading a situation (or reading the styles of the people involved ), you can help to create the right atmosphere for maximizing results. 
Apart from the purely judicial aspects, the British decision strikes a blow at the historic rights of other fishermen in the Community.


























## 7th Global Fisheries Enforcement Training Workshop (GFETW)
My name is Omar A. Mahadalle. I am a proactive young fisheries scientist with a proven track record of collaboration both with colleagues in senior role at FAO FIAF and also other organisations such as Secure Fisheries. Somalia lacks marine and fisheries and I am continually developing and executing a career preparation plan to help me quality for my Fisheries Enforcement.

I would appreciate your consideration regarding the possibility of wavering the attendance fee for him

Should you need official confirmation of this you can email me matthew.walsh@fao.org.

I believe that this would be a great opportunity for me to meet stakeholders, learn new skills and share ideas regarding Fisheries Enforcement.
I believe his attendance would be of benefit to all hence my efforts to assist his endeavours. He is currently based in the Philippines undertaking fisheries research at the Silliman University at Dumaguate.
I would appreciate your consideration regarding the possibility of wavering the attendance fee for him, however understand that due to budgetary requirements, this may not be possible.
Therefore , the mentoring experience for me would serve the dual role of enriching my technology skills and building my teaching skills .
I am interested in attending your workshop on recycled oil. Please send me further information as it becomes available .
I am continually developing and executing a career preparation plan to help me quality for my next targeted position.
Further develop the technical assistance skills and techniques of Federal staff, and identify and develop teahcnical assistance resources throughout the employment and training system. 
